### ISSUE TITLE
Stuck with .env database

### ISSUE THREAD

**Issue by zlatan14** [sarbull/timesheet#5]
Hi Sarbull,
I 'm newbie for Laravel. Now I install all of them and trying to run this code via Visual Studio Code.
I stuck with error as below
[PDOException]
  SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO)
With the command: php artisan migrate:install
For Wamp server and database with phpMyAdmin. I 've try to change username in addition to database, create the database is also. 
But still stuck.
Please suggest me for more in .ENV thank you.

**Comment by sarbull** [comment]
Hi @zlatan14,

Copy `https://github.com/sarbull/timesheet/blob/master/app/.env.example` into a `.env` file right near the `.env.example` and replace all variables inside with your credentials.

**Comment by zlatan14** [comment]
Hi again Sarbull
Now I could access to database but could you told me that the table for user.
Such as Char, or something? 
I 'm trying to define but still stuck please recommend one or two pages. thank you
http://s000.tinyupload.com/?file_id=82991732576053032194

**Comment by sarbull** [comment]
In laravel every database change is being made by a migration. Please check their documentation.
